# Generated by Django 5.2.7 on 2025-12-08 04:24

import django.db.models.deletion
import san_tms.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasks_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('task_frequency', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], default='Daily', max_length=20)),
                ('status', models.CharField(choices=[('Waiting', 'Waiting'), ('In Progress', 'In Progress'), ('Postponed', 'Postponed'), ('Overdue', 'Overdue'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Waiting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('next_date', models.DateTimeField(blank=True, null=True)),
                ('attachment', models.ImageField(blank=True, null=True, upload_to=san_tms.models.task_image_path)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tms_assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tms_created_tasks', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.departments')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_locations', to='accounts.location')),
            ],
            options={
                'verbose_name_plural': 'Tasks',
            },
        ),
        migrations.CreateModel(
            name='TasksRemarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('attachment', models.ImageField(blank=True, null=True, upload_to=san_tms.models.task_remark_image_path)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tms_created_remark', to=settings.AUTH_USER_MODEL)),
                ('tasks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='san_tms.tasks')),
            ],
            options={
                'verbose_name_plural': 'Tasks Remarks',
            },
        ),
        migrations.CreateModel(
            name='TasksTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_types', to='accounts.departments')),
            ],
            options={
                'verbose_name_plural': 'Tasks Types',
            },
        ),
        migrations.AddField(
            model_name='tasks',
            name='tasks_types',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='san_tms.taskstypes'),
        ),
    ]
