# Generated by Django 5.2.7 on 2026-05-01 09:17

import django.db.models.deletion
import django.utils.timezone
import san_tms.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tasks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tasks_number",
                    models.CharField(blank=True, max_length=20, unique=True),
                ),
                (
                    "task_frequency",
                    models.CharField(
                        choices=[
                            ("Daily", "Daily"),
                            ("Weekly", "Weekly"),
                            ("Monthly", "Monthly"),
                        ],
                        default="Daily",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Waiting", "Waiting"),
                            ("Acknowledged", "Acknowledged"),
                            ("In Progress", "In Progress"),
                            ("Postponed", "Postponed"),
                            ("Overdue", "Overdue"),
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Waiting",
                        max_length=20,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("next_date", models.DateTimeField(blank=True, null=True)),
                (
                    "attachment",
                    models.ImageField(
                        blank=True, null=True, upload_to=san_tms.models.task_image_path
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tms_assigned_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tms_created_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.departments",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks_locations",
                        to="accounts.location",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Tasks",
            },
        ),
        migrations.CreateModel(
            name="TaskHandover",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tms_handover_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "from_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tms_handover_from",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tms_handover_to",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tasks",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="handover_history",
                        to="san_tms.tasks",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Task Handovers",
            },
        ),
        migrations.CreateModel(
            name="TasksRemarks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("remarks", models.TextField()),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "attachment",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=san_tms.models.task_remark_image_path,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tms_created_remark",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tasks",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="san_tms.tasks"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Tasks Remarks",
            },
        ),
        migrations.CreateModel(
            name="TasksTypes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks_types",
                        to="accounts.departments",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Tasks Types",
            },
        ),
        migrations.AddField(
            model_name="tasks",
            name="tasks_types",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="san_tms.taskstypes",
            ),
        ),
        migrations.CreateModel(
            name="TaskChecklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_date", models.DateField(auto_now_add=True)),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist_task",
                        to="san_tms.taskstypes",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Task Checklist",
            },
        ),
    ]
