# Generated by Django 5.2.7 on 2026-05-02 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("san_tms", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taskchecklist",
            name="completed_by",
        ),
        migrations.RemoveField(
            model_name="taskchecklist",
            name="completed_date",
        ),
        migrations.RemoveField(
            model_name="taskchecklist",
            name="is_completed",
        ),
        migrations.CreateModel(
            name="TaskChecklistStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_date", models.DateTimeField(blank=True, null=True)),
                (
                    "checklist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="san_tms.taskchecklist",
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist_status",
                        to="san_tms.tasks",
                    ),
                ),
            ],
        ),
    ]
