# Generated by Django 5.2.7 on 2025-11-21 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('san_tms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'verbose_name_plural': 'Tasks'},
        ),
        migrations.AlterModelOptions(
            name='tasksremarks',
            options={'verbose_name_plural': 'Tasks Remarks'},
        ),
        migrations.AlterModelOptions(
            name='taskstypes',
            options={'verbose_name_plural': 'Tasks Types'},
        ),
    ]
