# Generated by Django 5.2 on 2025-06-16 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_location'),
        ('san_tms', '0002_alter_tasks_assigned_to_alter_tasks_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_locations', to='accounts.location'),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
