# Generated by Django 5.2.7 on 2025-12-01 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_tms', '0002_alter_tasks_options_alter_tasksremarks_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='waiting_time',
        ),
        migrations.AddField(
            model_name='tasks',
            name='task_frequency',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], default='Daily', max_length=20),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('In Progress', 'In Progress'), ('Postponed', 'Postponed'), ('Overdue', 'Overdue'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Waiting', max_length=20),
        ),
    ]
