# Generated by Codex on 2026-04-30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("san_tms", "0002_taskhandover"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasks",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
