# Generated by Codex on 2026-04-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("san_tms", "0003_tasks_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasks",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
    ]
