# Generated by Django 5.2 on 2025-06-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_tms', '0003_alter_tasks_location_delete_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('mid', 'Mid'), ('low', 'Low')], default='Low', max_length=20),
        ),
    ]
