# Generated by Django 5.2.7 on 2025-12-01 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('san_tms', '0003_remove_tasks_priority_remove_tasks_waiting_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='completed_at',
            new_name='next_date',
        ),
    ]
