# Generated by Django 5.2.7 on 2026-04-30 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("san_tms", "0003_tasks_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasks",
            name="status",
            field=models.CharField(
                choices=[
                    ("Waiting", "Waiting"),
                    ("Acknowledged", "Acknowledged"),
                    ("In Progress", "In Progress"),
                    ("Postponed", "Postponed"),
                    ("Overdue", "Overdue"),
                    ("Completed", "Completed"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Waiting",
                max_length=20,
            ),
        ),
    ]
