# Generated by Django 5.2.7 on 2026-04-30 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("san_tms", "0004_alter_tasks_created_at"),
        ("san_tms", "0004_alter_tasks_status"),
    ]

    operations = []
