# Generated by Django 5.2 on 2025-06-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_tms', '0004_tasks_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='tasks_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
