# Generated by Django 5.2.7 on 2026-04-30 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("san_tms", "0005_merge_20260430_1109"),
        ("san_tms", "0005_taskchecklistitem"),
    ]

    operations = []
