# Generated by Django 5.2 on 2025-07-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_tms', '0005_tasks_tasks_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('waiting', 'Waiting'), ('completed', 'Completed')], default='Open', max_length=20),
        ),
    ]
