# Generated by Django 5.2 on 2025-07-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_tms', '0006_alter_tasks_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='waiting_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
