# Generated by Django 5.2 on 2025-07-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_tms', '0007_tasks_waiting_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('waiting', 'Waiting'), ('review', 'Review'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='Open', max_length=20),
        ),
    ]
