# Generated by Django 5.2 on 2025-07-18 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_tms', '0008_alter_tasks_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='tasks_images/'),
        ),
    ]
