# Generated by Django 5.2 on 2025-07-18 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_tms', '0009_tasks_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksremarks',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='tasks/remark_images/'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='tasks/tasks_images/'),
        ),
    ]
