# Generated by Django 5.2 on 2025-07-26 08:20

import san_tms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_tms', '0010_tasksremarks_attachment_alter_tasks_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to=san_tms.models.task_image_path),
        ),
        migrations.AlterField(
            model_name='tasksremarks',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to=san_tms.models.task_remark_image_path),
        ),
    ]
