# Generated by Django 5.2.4 on 2025-08-04 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_tms', '0011_alter_tasks_attachment_alter_tasksremarks_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('waiting', 'Waiting'), ('review', 'Review'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('halt', 'Halt')], default='Open', max_length=20),
        ),
    ]
