# Generated by Django 5.2.7 on 2025-12-06 11:24

import django.db.models.deletion
import django.utils.timezone
import san_ams.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoryCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'AccessoryCategories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AssetCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'AssetCategories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ComponentCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'ComponentCategories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ConsumableCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'ConsumableCategories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LicenseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('product_key', models.CharField(max_length=255, unique=True)),
                ('purchase_date', models.DateField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField(default=django.utils.timezone.now)),
                ('buyer_name', models.CharField(max_length=100)),
                ('buyer_phone', models.CharField(max_length=15)),
                ('buyer_email', models.EmailField(max_length=254, unique=True)),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_expire', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'License',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AccessoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_number', models.CharField(max_length=50, unique=True)),
                ('manufacturer', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to=san_ams.models.accessory_image_path)),
                ('purchase_date', models.DateField(default=django.utils.timezone.now)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessory_category', to='san_ams.accessorycategorymodel')),
            ],
            options={
                'verbose_name_plural': 'Accessories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ComponentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to=san_ams.models.component_image_path)),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('model_number', models.CharField(max_length=50, unique=True)),
                ('manufacturer', models.CharField(max_length=100)),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('purchase_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_category', to='san_ams.componentcategorymodel')),
            ],
            options={
                'verbose_name_plural': 'Components',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ConsumableModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_number', models.CharField(max_length=50, unique=True)),
                ('manufacturer', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to=san_ams.models.consumable_image_path)),
                ('purchase_date', models.DateField(default=django.utils.timezone.now)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumable_category', to='san_ams.consumablecategorymodel')),
            ],
            options={
                'verbose_name_plural': 'Consumables',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AssetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('model_number', models.CharField(max_length=100, unique=True)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=san_ams.models.asset_image_path)),
                ('purchase_date', models.DateField(default=django.utils.timezone.now)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expiry_date', models.DateField(default=django.utils.timezone.now)),
                ('depreciation', models.PositiveIntegerField(default=5)),
                ('residual_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('deployed', 'Deployed'), ('ready to deploy', 'Ready to Deploy'), ('repair', 'Repair'), ('broken', 'Broken'), ('waiting', 'Waiting')], default='available', max_length=20)),
                ('resquestable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('asset_accessory', models.ManyToManyField(blank=True, related_name='asset_accessories', to='san_ams.accessorymodel')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_user', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_category', to='san_ams.assetcategorymodel')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_request_by', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_department', to='accounts.departments')),
                ('handler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_handler', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_location', to='accounts.location')),
                ('requested_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_request_to', to=settings.AUTH_USER_MODEL)),
                ('asset_component', models.ManyToManyField(blank=True, related_name='asset_components', to='san_ams.componentmodel')),
                ('asset_consumable', models.ManyToManyField(blank=True, related_name='asset_consumables', to='san_ams.consumablemodel')),
                ('asset_license', models.ManyToManyField(blank=True, related_name='asset_licenses', to='san_ams.licensemodel')),
            ],
            options={
                'verbose_name_plural': 'Assets',
                'ordering': ['name'],
            },
        ),
    ]
