# Generated by Django 5.2.7 on 2026-05-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("san_ams", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accessorycategorymodel",
            options={
                "ordering": ["name"],
                "verbose_name_plural": "Accessory Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="assetcategorymodel",
            options={"ordering": ["name"], "verbose_name_plural": "Asset Categories"},
        ),
        migrations.AlterModelOptions(
            name="componentcategorymodel",
            options={
                "ordering": ["name"],
                "verbose_name_plural": "Component Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="consumablecategorymodel",
            options={
                "ordering": ["name"],
                "verbose_name_plural": "Consumable Categories",
            },
        ),
        migrations.AlterField(
            model_name="assetmodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("AVAILABALE", "Available"),
                    ("REQUESTED", "Requested"),
                    ("DEPLOYED", "Deployed"),
                    ("ASSIGNED", "Assigned"),
                    ("REPAIR", "Repair"),
                    ("BROKEN", "Broken"),
                    ("WAITING", "Waiting"),
                    ("PANDING", "Panding"),
                ],
                default="AVAILABALE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="assetrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("AVAILABALE", "Available"),
                    ("REQUESTED", "Requested"),
                    ("DEPLOYED", "Deployed"),
                    ("ASSIGNED", "Assigned"),
                    ("REPAIR", "Repair"),
                    ("BROKEN", "Broken"),
                    ("WAITING", "Waiting"),
                    ("PANDING", "Panding"),
                ],
                default="PANDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="licensemodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("ASSIGNED", "Assigned"),
                    ("AVAILABLE", "Available"),
                    ("RENEWAL_DUE", "Renewal Due"),
                    ("EXPIRED", "Expired"),
                    ("REVOKED", "Revoked"),
                ],
                default="ACTIVE",
                max_length=20,
            ),
        ),
    ]
