# Generated by Django 5.2.7 on 2026-05-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("san_ams", "0002_alter_accessorycategorymodel_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assetmodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("AVAILABALE", "Available"),
                    ("REQUESTED", "Requested"),
                    ("DEPLOYED", "Deployed"),
                    ("ASSIGNED", "Assigned"),
                    ("REPAIR", "Repair"),
                    ("FAULTY", "Faulty"),
                    ("WAITING", "Waiting"),
                    ("PANDING", "Panding"),
                ],
                default="AVAILABALE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="assetrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("AVAILABALE", "Available"),
                    ("REQUESTED", "Requested"),
                    ("DEPLOYED", "Deployed"),
                    ("ASSIGNED", "Assigned"),
                    ("REPAIR", "Repair"),
                    ("FAULTY", "Faulty"),
                    ("WAITING", "Waiting"),
                    ("PANDING", "Panding"),
                ],
                default="PANDING",
                max_length=20,
            ),
        ),
    ]
