# Generated by Django 5.2.7 on 2025-12-09 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('san_ams', '0005_alter_assetmodel_depreciation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetmodel',
            name='residual_value',
        ),
    ]
