# Generated by Django 5.2.7 on 2025-12-09 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("san_ams", "0006_remove_assetmodel_residual_value"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assetmodel",
            name="depreciation",
        ),
    ]
