# Generated by Django 5.2.4 on 2025-09-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptioninfo',
            name='endpoint_name',
            field=models.CharField(default=None, max_length=500, unique=True),
        ),
    ]
