# Generated by Django 5.2.4 on 2025-09-22 05:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_subscriptioninfo_endpoint_name'),
        ('webpush', '0006_alter_subscriptioninfo_user_agent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubscriptionInfo',
            new_name='PushSubscription',
        ),
    ]
