# Generated by Django 5.2.7 on 2025-11-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_anonymousservicegenerate_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymousservicegenerate',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Waiting', 'Waiting'), ('Pending', 'Pending'), ('On Hold', 'On Hold'), ('Completed', 'Completed')], default='In Progress', max_length=20),
        ),
    ]
