# Generated by Django 5.2.4 on 2025-09-25 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_subscriptioninfo_pushsubscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PushSubscription',
        ),
    ]
