# Generated by Django 5.2.4 on 2025-09-01 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('san_srm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicetypes',
            options={'verbose_name_plural': 'Service Types'},
        ),
    ]
