# Generated by Django 5.2.7 on 2026-01-09 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_srm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='UHID',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
