# Generated by Django 5.2.4 on 2025-09-11 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_srm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_blocks', to='san_srm.blocks'),
        ),
    ]
