# Generated by Django 5.2.7 on 2025-11-21 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_srm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blocks',
            options={'ordering': ['name'], 'verbose_name_plural': 'Blocks'},
        ),
        migrations.AlterModelOptions(
            name='serviceremarks',
            options={'verbose_name_plural': 'Service Remarks'},
        ),
        migrations.AlterModelOptions(
            name='servicetypes',
            options={'verbose_name_plural': 'Service Types'},
        ),
        migrations.RemoveField(
            model_name='service',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='service',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, null=True, related_name='srm_service_staff', to='san_srm.shiftschedule'),
        ),
    ]
