# Generated by Django 5.2.7 on 2026-06-30 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("san_srm", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="request_type",
            field=models.CharField(
                choices=[("Critical", "Critical"), ("Normal", "Normal")],
                default="Low",
                max_length=20,
            ),
        ),
    ]
