# Generated by Django 5.2.7 on 2025-10-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_srm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymousservicegenerate',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('waiting', 'Waiting'), ('pending', 'Pending'), ('on hold', 'On Hold'), ('completed', 'Completed')], default='In Progress', max_length=20),
        ),
    ]
