# Generated by Django 5.2.4 on 2025-09-15 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_srm', '0002_service_service_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('waiting', 'Waiting'), ('pending', 'Pending'), ('on hold', 'On Hold'), ('completed', 'Completed')], default='Open', max_length=20),
        ),
    ]
