# Generated by Django 5.2.7 on 2025-11-21 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_srm', '0002_alter_blocks_options_alter_serviceremarks_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='service',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='srm_service_staff', to='san_srm.shiftschedule'),
        ),
    ]
