# Generated by Django 5.2.7 on 2025-10-02 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('san_srm', '0002_anonymousservicegenerate_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnonymousServiceGenerate',
        ),
    ]
