# Generated by Django 5.2.4 on 2025-09-03 10:46

import django.db.models.deletion
import san_srm.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_customusers_options_alter_location_options'),
        ('san_srm', '0002_alter_servicetypes_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicetypes',
            options={},
        ),
        migrations.RemoveField(
            model_name='service',
            name='location',
        ),
        migrations.AddField(
            model_name='service',
            name='from_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_from', to='accounts.location'),
        ),
        migrations.AddField(
            model_name='service',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('mid', 'Mid'), ('low', 'Low')], default='Low', max_length=20),
        ),
        migrations.AddField(
            model_name='service',
            name='to_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_to', to='accounts.location'),
        ),
        migrations.CreateModel(
            name='GenerateService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generate_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('generate_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('attachment', models.ImageField(blank=True, null=True, upload_to=san_srm.models.generate_service_image_path)),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generate_from', to='accounts.location')),
                ('generate_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='srm_generate_service', to=settings.AUTH_USER_MODEL)),
                ('service_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='san_srm.servicetypes')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generate_to', to='accounts.location')),
            ],
        ),
    ]
