# Generated by Django 5.2.4 on 2025-09-06 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_srm', '0003_alter_servicetypes_options_remove_service_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_block', to='san_srm.blocks')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='generateservice',
            name='from_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generate_from', to='san_srm.servicelocation'),
        ),
        migrations.AlterField(
            model_name='generateservice',
            name='to_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generate_to', to='san_srm.servicelocation'),
        ),
        migrations.AlterField(
            model_name='service',
            name='from_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_from', to='san_srm.servicelocation'),
        ),
        migrations.AlterField(
            model_name='service',
            name='to_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_to', to='san_srm.servicelocation'),
        ),
        migrations.CreateModel(
            name='ServiceRequestQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_queue', to='san_srm.service')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShiftSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_type', models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening'), ('day', 'Day'), ('night', 'Night')], default='Morning', max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('shift_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_locationss', to='san_srm.servicelocation')),
                ('shift_staffs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_staff', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='generateservice',
            name='generate_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='srm_generate_service', to='san_srm.shiftschedule'),
        ),
        migrations.AlterField(
            model_name='service',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='srm_service_staff', to='san_srm.shiftschedule'),
        ),
    ]
