# Generated by Django 5.2.4 on 2025-09-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_srm', '0003_alter_service_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='generateservice',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('waiting', 'Waiting'), ('pending', 'Pending'), ('on hold', 'On Hold'), ('completed', 'Completed')], default='In Progress', max_length=20),
        ),
    ]
