# Generated by Django 5.2.7 on 2025-11-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_srm', '0003_remove_service_assigned_to_service_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
