# Generated by Django 5.2.4 on 2025-09-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_srm', '0004_generateservice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
