# Generated by Django 5.2.4 on 2025-09-10 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_srm', '0004_blocks_servicelocation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftschedule',
            name='shift_staffs',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('department__name', 'GDA'), ('department__name', 'General Duty Assistant'), _connector='OR'), ('role', 'User')), on_delete=django.db.models.deletion.CASCADE, related_name='shift_staff', to=settings.AUTH_USER_MODEL),
        ),
    ]
