# Generated by Django 5.2.7 on 2026-02-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_srm', '0005_service_handled_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, default='enter description here', max_length=100, null=True),
        ),
    ]
