# Generated by Django 5.2.7 on 2025-11-25 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_srm', '0005_alter_generateservice_status_alter_service_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='priority',
        ),
        migrations.AddField(
            model_name='service',
            name='UHID',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(default='type here'),
        ),
    ]
