# Generated by Django 5.2.7 on 2025-11-25 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_srm', '0006_remove_service_priority_service_uhid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(default='enter description here', max_length=100),
        ),
    ]
