# Generated by Django 5.2.7 on 2026-03-03 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("san_srm", "0006_alter_service_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="hold_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
