# Generated by Django 5.2.7 on 2026-03-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("san_srm", "0007_service_hold_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="hold_at",
        ),
        migrations.AddField(
            model_name="service",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="hold_used",
            field=models.BooleanField(default=False),
        ),
    ]
