# Generated by Django 5.2.7 on 2025-11-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_srm', '0007_alter_service_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generateservice',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Waiting', 'Waiting'), ('Pending', 'Pending'), ('On Hold', 'On Hold'), ('Completed', 'Completed')], default='Completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Waiting', 'Waiting'), ('Pending', 'Pending'), ('On Hold', 'On Hold'), ('Completed', 'Completed')], default='Open', max_length=20),
        ),
    ]
