# Generated by Django 5.2.7 on 2026-03-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("san_srm", "0008_remove_service_hold_at_service_deadline_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shiftschedule",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
