# Generated by Django 5.2.7 on 2026-03-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("san_srm", "0009_shiftschedule_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shiftschedule",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
