# Generated by Django 5.2.7 on 2026-03-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("san_srm", "0010_alter_shiftschedule_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="request_type",
            field=models.CharField(
                choices=[("Critical", "Critical"), ("High", "High"), ("Low", "Low")],
                default="Low",
                max_length=20,
            ),
        ),
    ]
