# Generated by Django 5.2.7 on 2026-04-04 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("san_srm", "0011_service_request_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shiftschedule",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
