# Generated by Django 5.2.4 on 2025-09-11 05:08

import django.db.models.deletion
import san_cms.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('review', 'Review'), ('rejected', 'Rejected'), ('open', 'Open'), ('cancelled', 'Cancelled'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('halt', 'Halt'), ('waiting', 'Waiting')], default='Open', max_length=20)),
                ('priority', models.CharField(choices=[('high', 'High'), ('mid', 'Mid'), ('low', 'Low')], default='Low', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('attachment', models.ImageField(blank=True, null=True, upload_to=san_cms.models.complaint_image_path)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cms_assigned_complaints', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_created_complaints', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.departments')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaint_locations', to='accounts.location')),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_changed_to', models.CharField(choices=[('review', 'Review'), ('rejected', 'Rejected'), ('open', 'Open'), ('cancelled', 'Cancelled'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('halt', 'Halt'), ('waiting', 'Waiting')], default='Open', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changed_complaints', to=settings.AUTH_USER_MODEL)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='san_cms.complaint')),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintRemarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('attachment', models.ImageField(blank=True, null=True, upload_to=san_cms.models.complaint_remark_image_path)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='san_cms.complaint')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cms_created_remark', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_types', to='accounts.departments')),
            ],
        ),
        migrations.AddField(
            model_name='complaint',
            name='complaint_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='san_cms.complainttype'),
        ),
        migrations.CreateModel(
            name='ReassignDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='san_cms.complaint')),
                ('reassign_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reassign_departments', to='accounts.departments')),
            ],
        ),
        migrations.CreateModel(
            name='ReassignedComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(choices=[('00:03', '3 min'), ('00:30', '30 min'), ('01:00', '1 hr'), ('01:30', '1 hr 30 min'), ('02:00', '2 hr'), ('02:30', '2 hr 30 min'), ('03:00', '3 hr'), ('03:30', '3 hr 30 min')], default='00:00', max_length=5, verbose_name='Duration')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='san_cms.complaint')),
                ('reassigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reassign_complaints', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
