# Generated by Django 5.2.7 on 2025-11-21 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('san_cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaintremarks',
            options={'verbose_name_plural': 'Complaint Remarks'},
        ),
    ]
