# Generated by Django 5.2 on 2025-06-16 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_location'),
        ('san_cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaint_locations', to='accounts.location'),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
