# Generated by Django 5.2.7 on 2026-05-29 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("san_cms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reassignedcomplaint",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
