# Generated by Django 5.2.7 on 2026-05-29 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("san_cms", "0002_reassignedcomplaint_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reassignedcomplaint",
            name="message",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
