# Generated by Django 5.2 on 2025-06-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_cms', '0002_alter_complaint_location_delete_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='shown_to_assigned_user',
            field=models.BooleanField(default=False),
        ),
    ]
