# Generated by Django 5.2.7 on 2026-05-29 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("san_cms", "0003_alter_reassignedcomplaint_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="reassigndepartment",
            name="reason",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
