# Generated by Django 5.2 on 2025-06-23 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('san_cms', '0003_complaint_shown_to_assigned_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='shown_to_assigned_user',
        ),
    ]
