# Generated by Django 5.2 on 2025-06-24 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_cms', '0004_remove_complaint_shown_to_assigned_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('mid', 'Mid'), ('low', 'Low')], default='Low', max_length=20),
        ),
    ]
