# Generated by Django 5.2.7 on 2026-05-30 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("san_cms", "0004_reassigndepartment_reason"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Facility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Facilities",
            },
        ),
        migrations.AlterField(
            model_name="complaint",
            name="status",
            field=models.CharField(
                choices=[
                    ("review", "Review"),
                    ("rejected", "Rejected"),
                    ("open", "Open"),
                    ("cancelled", "Cancelled"),
                    ("acknoledged", "Acknowledged"),
                    ("in_progress", "In Progress"),
                    ("resolved", "Resolved"),
                    ("halt", "Halt"),
                    ("waiting", "Waiting"),
                ],
                default="Open",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="complainthistory",
            name="status_changed_to",
            field=models.CharField(
                choices=[
                    ("review", "Review"),
                    ("rejected", "Rejected"),
                    ("open", "Open"),
                    ("cancelled", "Cancelled"),
                    ("acknoledged", "Acknowledged"),
                    ("in_progress", "In Progress"),
                    ("resolved", "Resolved"),
                    ("halt", "Halt"),
                    ("waiting", "Waiting"),
                ],
                default="Open",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "block_admin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="san_cms.facility",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Complaint Blocks",
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="san_cms.block"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Locations",
            },
        ),
        migrations.AlterField(
            model_name="complaint",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="complaint_locations",
                to="san_cms.location",
            ),
        ),
    ]
