# Generated by Django 5.2 on 2025-06-25 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_cms', '0005_complaint_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
