# Generated by Django 5.2.7 on 2026-05-30 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("san_cms", "0005_facility_alter_complaint_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="block",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="complaint_blocks",
                to="san_cms.block",
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="facility",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="complaint_facilities",
                to="san_cms.facility",
            ),
        ),
    ]
