# Generated by Django 5.2 on 2025-06-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_cms', '0006_complaint_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='complaint_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
