# Generated by Django 5.2.7 on 2026-05-30 06:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("san_cms", "0006_complaint_block_complaint_facility"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="assigned_to_many",
            field=models.ManyToManyField(
                blank=True,
                related_name="cms_assigned_complaints_many",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="status",
            field=models.CharField(
                choices=[
                    ("review", "Review"),
                    ("rejected", "Rejected"),
                    ("open", "Open"),
                    ("cancelled", "Cancelled"),
                    ("acknowledged", "Acknowledged"),
                    ("in_progress", "In Progress"),
                    ("resolved", "Resolved"),
                    ("halt", "Halt"),
                    ("waiting", "Waiting"),
                ],
                default="Open",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="complainthistory",
            name="status_changed_to",
            field=models.CharField(
                choices=[
                    ("review", "Review"),
                    ("rejected", "Rejected"),
                    ("open", "Open"),
                    ("cancelled", "Cancelled"),
                    ("acknowledged", "Acknowledged"),
                    ("in_progress", "In Progress"),
                    ("resolved", "Resolved"),
                    ("halt", "Halt"),
                    ("waiting", "Waiting"),
                ],
                default="Open",
                max_length=20,
            ),
        ),
    ]
