# Generated by Django 5.2 on 2025-06-28 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_cms', '0007_complaint_complaint_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='complaint_images/'),
        ),
    ]
