# Generated by Django 5.2.7 on 2026-05-30 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("san_cms", "0007_complaint_assigned_to_many_alter_complaint_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="complaint",
            name="assigned_to_many",
        ),
    ]
