# Generated by Django 5.2 on 2025-06-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_cms', '0008_complaint_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='in_progress_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
