# Generated by Django 5.2 on 2025-06-29 06:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_cms', '0010_alter_complaint_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='reassignedcomplaint',
            name='reassigned_to',
        ),
        migrations.AddField(
            model_name='complaint',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='cms_assigned_complaints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reassignedcomplaint',
            name='reassigned_to',
            field=models.ManyToManyField(related_name='reassigned_complaints', to=settings.AUTH_USER_MODEL),
        ),
    ]
