# Generated by Django 5.2.7 on 2026-06-30 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("san_cms", "0010_departmentblockadmin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="block",
            name="block_admin",
        ),
    ]
