# Generated by Django 5.2 on 2025-06-29 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customusers_email_alter_customusers_is_active'),
        ('san_cms', '0012_remove_complaint_assigned_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReassignedComplaintToDepartments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='san_cms.complaint')),
                ('reassigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reassign_complaints_departments', to='accounts.departments')),
            ],
        ),
    ]
