# Generated by Django 5.2 on 2025-06-29 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('san_cms', '0013_reassignedcomplainttodepartments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reassignedcomplainttodepartments',
            old_name='reassigned_to',
            new_name='reassigned_to_dept',
        ),
    ]
