# Generated by Django 5.2 on 2025-06-29 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('san_cms', '0014_rename_reassigned_to_reassignedcomplainttodepartments_reassigned_to_dept'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReassignedComplaintToDepartments',
        ),
    ]
