# Generated by Django 5.2 on 2025-06-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_cms', '0015_delete_reassignedcomplainttodepartments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('review', 'Review'), ('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled'), ('halt', 'Halt')], default='Open', max_length=20),
        ),
        migrations.AlterField(
            model_name='complainthistory',
            name='status_changed_to',
            field=models.CharField(choices=[('review', 'Review'), ('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled'), ('halt', 'Halt')], default='Open', max_length=20),
        ),
    ]
