# Generated by Django 5.2 on 2025-07-04 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_cms', '0017_alter_complaint_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintremarks',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='remark_images/'),
        ),
    ]
