# Generated by Django 5.2 on 2025-07-07 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_cms', '0018_complaintremarks_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='reassignedcomplaint',
            name='duration',
            field=models.CharField(choices=[('00:30', '30 min'), ('01:00', '1 hr'), ('01:30', '1 hr 30 min'), ('02:00', '2 hr'), ('02:30', '2 hr 30 min'), ('03:00', '3 hr'), ('03:30', '3 hr 30 min')], default='00:00', max_length=5, verbose_name='Duration'),
        ),
    ]
