# Generated by Django 5.2 on 2025-07-07 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_cms', '0019_reassignedcomplaint_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('review', 'Review'), ('rejected', 'Rejected'), ('open', 'Open'), ('cancelled', 'Cancelled'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('halt', 'Halt'), ('waiting', 'Waiting')], default='Open', max_length=20),
        ),
        migrations.AlterField(
            model_name='complainthistory',
            name='status_changed_to',
            field=models.CharField(choices=[('review', 'Review'), ('rejected', 'Rejected'), ('open', 'Open'), ('cancelled', 'Cancelled'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('halt', 'Halt'), ('waiting', 'Waiting')], default='Open', max_length=20),
        ),
    ]
