# Generated by Django 5.2 on 2025-07-07 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customusers_employee_id'),
        ('san_cms', '0020_alter_complaint_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReassignDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='san_cms.complaint')),
                ('reassigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reassign_departments', to='accounts.departments')),
            ],
        ),
    ]
