# Generated by Django 5.2 on 2025-07-07 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('san_cms', '0021_reassigndepartment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reassigndepartment',
            old_name='reassigned_to',
            new_name='reassign_to',
        ),
    ]
