# Generated by Django 5.2 on 2025-07-08 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('san_cms', '0022_rename_reassigned_to_reassigndepartment_reassign_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='in_progress_time',
        ),
    ]
