# Generated by Django 5.2 on 2025-07-18 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_cms', '0023_remove_complaint_in_progress_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='complaints/complaint_images/'),
        ),
        migrations.AlterField(
            model_name='complaintremarks',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='complaints/remark_images/'),
        ),
    ]
