# Generated by Django 5.2 on 2025-07-24 04:23

import san_cms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_cms', '0024_alter_complaint_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to=san_cms.models.complaint_image_path),
        ),
    ]
