# Generated by Django 5.2.7 on 2026-05-01 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vehicle_number", models.CharField(max_length=50, unique=True)),
                ("vehicle_type", models.CharField(max_length=50)),
                ("capacity_weight", models.FloatField(blank=True, null=True)),
                ("capacity_volume", models.FloatField(blank=True, null=True)),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("DIESEL", "Diesel"),
                            ("PETROL", "Petrol"),
                            ("ELECTRIC", "Electric"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("BOOKED", "Booked"),
                            ("IN_TRANSIT", "In Transit"),
                            ("UNDER_REPAIR", "Under Repair"),
                            ("INACTIVE", "Inactive"),
                        ],
                        default="AVAILABLE",
                        max_length=20,
                    ),
                ),
                ("maintenance_due_date", models.DateField(blank=True, null=True)),
                ("is_emergency_active", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("license_number", models.CharField(max_length=50)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driver_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Users",
                "ordering": ["user__username"],
            },
        ),
        migrations.CreateModel(
            name="DriverSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shift_type",
                    models.CharField(
                        choices=[
                            ("morning", "Morning"),
                            ("evening", "Evening"),
                            ("day", "Day"),
                            ("night", "Night"),
                        ],
                        default="Morning",
                        max_length=20,
                    ),
                ),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("ongoing", "Ongoing"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "shift_staffs",
                    models.ForeignKey(
                        limit_choices_to=models.Q(
                            ("user__department__name__iexact", "Transport"),
                            ("user__role", "User"),
                        ),
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shift_staff",
                        to="san_vms.driver",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VehicleMaintenance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="san_vms.vehicle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "booking_type",
                    models.CharField(
                        choices=[
                            ("DROP", "Drop"),
                            ("PICKUP", "Pickup"),
                            ("DROP_AND_PICKUP", "Drop and Pickup"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="NORMAL",
                        max_length=20,
                    ),
                ),
                (
                    "department_priority",
                    models.IntegerField(
                        default=0, help_text="Higher value = higher priority department"
                    ),
                ),
                ("pickup_location", models.CharField(max_length=255)),
                ("drop_location", models.CharField(blank=True, max_length=255)),
                ("pickup_time", models.DateTimeField(blank=True, null=True)),
                ("drop_time", models.DateTimeField(blank=True, null=True)),
                ("passengers", models.IntegerField(blank=True, default=0, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_recurring", models.BooleanField(default=False)),
                (
                    "recurrence_pattern",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("MONTHLY", "Monthly"),
                        ],
                        default="DAILY",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("WAITING", "Waiting"),
                            ("CONFIRMED", "Confirmed"),
                            ("ACKNOWLEDGE", "Acknowledge"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="WAITING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bookings_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "booked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bookings_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bookings_driver",
                        to="san_vms.driver",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bookings",
                        to="san_vms.vehicle",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("status__in", ["CONFIRMED", "IN_PROGRESS"])
                        ),
                        fields=("vehicle",),
                        name="unique_active_booking_per_vehicle",
                    )
                ],
            },
        ),
    ]
