# Generated by Django 5.2.7 on 2026-02-09 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_type', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('volume', models.FloatField()),
                ('fragile', models.BooleanField(default=False)),
                ('refrigeration_required', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=50, unique=True)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('capacity_weight', models.FloatField(blank=True, null=True)),
                ('capacity_volume', models.FloatField(blank=True, null=True)),
                ('fuel_type', models.CharField(choices=[('DIESEL', 'Diesel'), ('PETROL', 'Petrol'), ('ELECTRIC', 'Electric')], max_length=20)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('IN_TRANSIT', 'In Transit'), ('UNDER_REPAIR', 'Under Repair'), ('INACTIVE', 'Inactive')], default='AVAILABLE', max_length=20)),
                ('current_location', models.CharField(blank=True, max_length=255)),
                ('maintenance_due_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_type', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ON_DUTY', 'On Duty'), ('OFF_DUTY', 'Off Duty')], default='AVAILABLE', max_length=20)),
                ('shift_start', models.TimeField()),
                ('shift_end', models.TimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_type', models.CharField(choices=[('DROP', 'Drop'), ('PICKUP', 'Pickup'), ('DROP_AND_PICKUP', 'Drop and Pickup')], max_length=20)),
                ('pickup_location', models.CharField(max_length=255)),
                ('drop_location', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='CONFIRMED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings_user', to=settings.AUTH_USER_MODEL)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='san_vms.cargo')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings_driver', to='san_vms.driver')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='san_vms.slot')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='san_vms.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='san_vms.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='DriverSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='san_vms.booking')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='san_vms.driver')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='san_vms.slot')),
            ],
            options={
                'unique_together': {('driver', 'slot')},
            },
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('vehicle__isnull', False)), fields=('slot', 'vehicle'), name='unique_vehicle_per_slot'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('driver__isnull', False)), fields=('slot', 'driver'), name='unique_driver_per_slot'),
        ),
    ]
