# Generated by Django 5.2.7 on 2026-04-18 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("san_vms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driverschedule",
            name="shift_staffs",
            field=models.ForeignKey(
                limit_choices_to=models.Q(
                    ("user__department__name__iexact", "Transport"),
                    ("user__role", "User"),
                ),
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shift_staff",
                to="san_vms.driver",
            ),
        ),
    ]
