# Generated by Django 5.2.7 on 2026-02-12 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_vms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='department_priority',
            field=models.IntegerField(default=0, help_text='Higher value = higher priority department'),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='priority',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='NORMAL', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='recurrence_pattern',
            field=models.CharField(blank=True, help_text='Example: DAILY, WEEKLY_MON, WEEKLY_FRI', max_length=50),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='is_emergency_active',
            field=models.BooleanField(default=False),
        ),
    ]
