# Generated by Django 5.2.7 on 2026-02-12 09:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("san_vms", "0002_booking_department_priority_booking_is_recurring_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicle",
            name="current_location",
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["CONFIRMED", "IN_PROGRESS"])),
                fields=("vehicle",),
                name="unique_active_booking_per_vehicle",
            ),
        ),
    ]
