# Generated by Django 5.2.7 on 2026-04-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("san_vms", "0002_alter_driverschedule_shift_staffs"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="passengers",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
