# Generated by Django 5.2.7 on 2026-06-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("san_vms", "0002_patientbooking_patientpayment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientbooking",
            name="booked_by",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
