# Generated by Django 5.2.7 on 2026-06-06 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("san_vms", "0003_alter_patientbooking_booked_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patientbooking",
            name="scheduled_drop_time",
        ),
    ]
