# Generated by Django 5.2.7 on 2026-04-18 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("san_vms", "0003_booking_description_booking_passengers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="cargo",
        ),
        migrations.DeleteModel(
            name="Cargo",
        ),
    ]
