# Generated by Django 5.2.7 on 2026-06-06 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("san_vms", "0004_remove_patientbooking_scheduled_drop_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientpayment",
            name="qr_code_image",
            field=models.ImageField(blank=True, null=True, upload_to="payment_qr/"),
        ),
        migrations.AddField(
            model_name="patientpayment",
            name="upi_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="patientpayment",
            name="upi_transaction_ref",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
