# Generated by Django 5.2.7 on 2026-04-20 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("san_vms", "0004_remove_booking_cargo_delete_cargo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="recurrence_pattern",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DAILY", "Daily"),
                    ("WEEKLY", "Weekly"),
                    ("MONTHLY", "Monthly"),
                ],
                default="DAILY",
                max_length=20,
                null=True,
            ),
        ),
    ]
