# Generated by Django 5.2.7 on 2026-04-30 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("san_vms", "0005_alter_booking_recurrence_pattern"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="driver",
            options={"ordering": ["user__username"], "verbose_name_plural": "Users"},
        ),
    ]
