# Generated by Django 5.2.7 on 2026-02-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_vms', '0005_remove_driver_shift_end_remove_driver_shift_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('ENGAGED', 'Engaged'), ('OFF_DUTY', 'Off Duty')], default='AVAILABLE', max_length=20),
        ),
    ]
