# Generated by Django 5.2.7 on 2026-06-30 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("san_vms", "0005_patientpayment_qr_code_image_patientpayment_upi_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="priority",
            field=models.CharField(
                choices=[("NORMAL", "Normal"), ("URGENT", "Urgent")],
                default="NORMAL",
                max_length=20,
            ),
        ),
    ]
