# Generated by Django 5.2.7 on 2026-02-13 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('san_vms', '0006_alter_driver_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='status',
        ),
    ]
