# Generated by Django 5.2.7 on 2026-03-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("san_vms", "0007_remove_driver_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("WAITING", "Waiting"),
                    ("CONFIRMED", "Confirmed"),
                    ("ACKNOWLEDGE", "Acknowledge"),
                    ("IN_PROGRESS", "In Progress"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="WAITING",
                max_length=20,
            ),
        ),
    ]
