# Generated by Django 5.2.7 on 2026-02-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customusers",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
