# Generated by Django 5.2.7 on 2025-11-21 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customusers',
            options={'ordering': ['username'], 'verbose_name_plural': 'Custom Users'},
        ),
        migrations.AlterModelOptions(
            name='departments',
            options={'ordering': ['name'], 'verbose_name_plural': 'Departments'},
        ),
    ]
