# Generated by Django 5.2 on 2025-05-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='status',
            field=models.CharField(blank=True, choices=[('Engaged', 'engaged'), ('Vacant', 'vacant')], default='vacant', max_length=25, null=True),
        ),
    ]
