# Generated by Django 5.2 on 2025-06-29 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customusers_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
