# Generated by Django 5.2 on 2025-07-01 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customusers_email_alter_customusers_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='employee_id',
            field=models.CharField(default='EMP_ID', max_length=20, unique=True),
        ),
    ]
