# Generated by Django 5.2 on 2025-07-28 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customusers_employee_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departments',
            options={'ordering': ['name']},
        ),
    ]
