# Generated by Django 5.2.4 on 2025-07-28 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_departments_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customusers',
            options={'ordering': ['username']},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name']},
        ),
    ]
