# Generated by Django 5.2.4 on 2025-09-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_customusers_options_alter_location_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='status',
            field=models.CharField(blank=True, choices=[('engaged', 'Engaged'), ('vacant', 'Vacant')], default='vacant', max_length=25, null=True),
        ),
    ]
